object Dependencies {

    object UIcomponent {
        const val core = "androidx.core:core-ktx:1.10.1"
        const val appcompat = "androidx.appcompat:appcompat:1.6.1"
        const val constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
        const val legacy = "androidx.legacy:legacy-support-v4:1.0.0"
        const val androidMaterial =  "com.google.android.material:material:1.9.0"
        const val junit = "junit:junit:4.13.2"
        const val junitTest = "androidx.test.ext:junit:1.1.5"
        const val espresso = "androidx.test.espresso:espresso-core:3.5.1"
    }

    const val glade = "com.github.bumptech.glide:glide:${Versions.glide}"
    const val hilt = "com.google.dagger:hilt-android:${Versions.hilt}"
    const val livedata = "androidx.lifecycle:lifecycle-livedata-ktx:${Versions.livedata}"
    const val lifecycle = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.livedata}"
    const val hiltCompiler = "com.google.dagger:hilt-android-compiler:${Versions.hilt}"
    const val hiltNavigation = "androidx.hilt:hilt-navigation-fragment:${Versions.hiltNavigation}"
    const val activity = "androidx.activity:activity-ktx:${Versions.activity}"
    const val fragment = "androidx.fragment:fragment-ktx:${Versions.fragment}"
    const val navigationFragment = "androidx.navigation:navigation-fragment-ktx:${Versions.navigation}"
    const val navigationUI = "androidx.navigation:navigation-ui-ktx:${Versions.navigation}"
    const val navigationDynamic = "androidx.navigation:navigation-dynamic-features-fragment:${Versions.navigation}"
    const val paging = "androidx.paging:paging-runtime-ktx:${Versions.paging}"
    const val pagingComon = "androidx.paging:paging-common:${Versions.paging}"
    const val viewbinding = "com.github.kirich1409:viewbindingpropertydelegate-noreflection:${Versions.viewbinding}"
    const val lifecycleRuntime = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.livedata}"
    const val coordinatorlayout = "androidx.coordinatorlayout:coordinatorlayout:${Versions.coordinatorlayout}"
    const val materialComponents = "com.google.android.material:material:${Versions.materialComponents}"
    const val circleImageView = "de.hdodenhof:circleimageview:${Versions.circleImageView}"
    const val splashscreen = "androidx.core:core-splashscreen:${Versions.splashscreen}"
    const val dotsindicator = "com.tbuonomo:dotsindicator:${Versions.dotsindicator}"
    const val koin = "io.insert-koin:koin-android:${Versions.koin}"
    const val koinCom = "io.insert-koin:koin-core:${Versions.koinCom}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val retrofitConverter = "com.squareup.retrofit2:converter-gson:${Versions.retrofit}"
    const val okhttp3 = "com.squareup.okhttp3:okhttp-bom:${Versions.okhttp3}"
    const val okhttp = "com.squareup.okhttp3:okhttp"
    const val httpInterceptor = "com.squareup.okhttp3:logging-interceptor"
    const val javax = "javax.inject:javax.inject:1"
    const val coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutines}"
}