object Versions {

    const val application = "8.1.0"
    const val kotlinAndroid = "1.8.0"
    const val androidLibrary = "8.1.0"
    const val kotlinJvm = "1.8.0"
    const val hilt = "2.44"
    const val glide = "4.15.0"
    const val livedata = "2.6.1"
    const val hiltNavigation = "1.0.0"
    const val activity = "1.7.2"
    const val fragment = "1.6.1"
    const val navigation = "2.6.0"
    const val paging = "3.2.0"
    const val viewbinding = "1.5.8"
    const val coordinatorlayout = "1.2.0"
    const val materialComponents = "1.9.0"
    const val circleImageView = "3.1.0"
    const val splashscreen = "1.0.1"
    const val dotsindicator = "5.0"
    const val koin = "3.4.0"
    const val koinCom = "3.4.0"
    const val retrofit = "2.9.0"
    const val okhttp3 = "5.0.0-alpha.6"
    const val coroutines = "1.7.1"
}